nodes:
  - [0.75, 0.75, 0]
  - [1.15, 0.5, 1]
  - [2.0, 0.5, 2]
  - [2.85, 0.5, 3]
  - [3.5, 0.5, 4]
  - [4.15, 0.5, 5]
  - [5.0, 0.5, 6]
  - [6.0, 0.5, 7]
  - [6.5, 0.6, 8]
  - [7.0, 0.8, 9]
  - [7.25, 1.0, 10]
  - [7.5, 1.5, 11]

  - [7.25, 2.0, 12]
  - [7.0, 2.2, 13]
  - [6.5, 2.4, 14]
  - [6.0, 2.5, 15]
  - [5.0, 2.5, 16]
  - [4.15, 2.5, 17]
  - [3.75, 2.75, 18]
  - [3.5, 3.15, 19]
  - [3.5, 3.85, 20]
  - [3.5, 4.5, 21]
  - [3.5, 5.15, 22]
  - [3.5, 5.85, 23]
  - [3.4, 6.45, 24]
  - [3.0, 7.0, 25]
  - [2.55, 7.35, 26]
  - [2.0, 7.5, 27]
  - [1.45, 7.35, 28]
  - [1.0, 7.0, 29]
  - [0.6, 6.45, 30]
  - [0.5, 5.85, 31]
  - [0.5, 5.15, 32]
  - [0.5, 4.5, 33]
  - [0.5, 3.85, 34]
  - [0.5, 3.15, 35]
  - [0.5, 2.5, 36]
  - [0.5, 1.85, 37]
  - [0.5, 1.15, 38]

  - [0.75, 4.25, 39]
  - [0.75, 4.75, 40]
  - [1.15, 4.5, 41]
  - [2.0, 4.5, 42]
  - [2.85, 4.5, 43]
  - [3.25, 4.75, 44]
  - [3.25, 4.25, 45]

  - [0.75, 2.25, 46]
  - [0.75, 2.75, 47]
  - [1.15, 2.5, 48]
  - [2.0, 2.5, 49]
  - [2.85, 2.5, 50]
  - [3.25, 2.75, 51]
  - [3.25, 2.25, 52]
  - [3.5, 1.85, 53]
  - [3.5, 1.15, 54]
  - [3.25, 0.75, 55]
  - [3.75, 0.75, 56]
  - [3.75, 2.25, 57]
  - [3.5, 2.5, 58]

 
edges:
  - [0, 1, 0.471699]
  - [1, 2, 0.85]
  - [2, 3, 0.85]
  - [3, 4, 0.65]
  - [4, 5, 0.65]
  - [5, 6, 0.85]
  - [6, 7, 1.0]
  - [7, 8, 0.509902]
  - [8, 9, 0.538516]
  - [9, 10, 0.320156]
  - [10, 11, 0.559017]
  - [11, 12, 0.559017]
  - [12, 13, 0.320156]
  - [13, 14, 0.538516]
  - [14, 15, 0.509902]
  - [15, 16, 1.0]
  - [16, 17, 0.85]
  - [17, 18, 0.471699]
  - [18, 19, 0.471699]
  - [19, 20, 0.7]
  - [20, 21, 0.65]
  - [21, 22, 0.65]
  - [22, 23, 0.7]
  - [23, 24, 0.608276]
  - [24, 25, 0.680074]
  - [25, 26, 0.570088]
  - [26, 27, 0.570088]
  - [27, 28, 0.570088]
  - [28, 29, 0.570088]
  - [29, 30, 0.680074]
  - [30, 31, 0.608276]
  - [31, 32, 0.7]
  - [32, 33, 0.65]
  - [33, 34, 0.65]
  - [34, 35, 0.7]
  - [35, 36, 0.65]
  - [36, 37, 0.65]
  - [37, 38, 0.7]
  - [38, 0, 0.471699]
  - [32, 40, 0.471699]
  - [40, 41, 0.471699]
  - [41, 42, 0.85]
  - [42, 43, 0.85]
  - [43, 44, 0.471699]
  - [44, 22, 0.471699]
  - [34, 39, 0.471699]
  - [39, 41, 0.471699]
  - [43, 45, 0.471699]
  - [45, 20, 0.471699]
  - [35, 47, 0.471699]
  - [47, 48, 0.471699]
  - [48, 49, 0.85]
  - [49, 50, 0.85]
  - [50, 51, 0.471699]
  - [51, 19, 0.471699]
  - [37, 46, 0.471699]
  - [46, 48, 0.471699]
  - [50, 52, 0.471699]
  - [52, 53, 0.471699]
  - [53, 54, 0.7]
  - [54, 55, 0.471699]
  - [55, 3, 0.471699]
  - [54, 56, 0.471699]
  - [56, 5, 0.471699]
  - [53, 57, 0.471699]
  - [57, 17, 0.471699]
  - [53, 58, 0.65]
  - [50, 58, 0.65]
  - [19, 58, 0.65]
  - [17, 58, 0.65]
  - [33, 41, 0.65]
  - [21, 43, 0.65]
  - [36, 48, 0.65]
  - [4, 54, 0.65]
  - [44, 45, 0.5]
  - [39, 40, 0.5]
  - [46, 47, 0.5]
  - [55, 56, 0.5]
  - [57, 18, 0.5]
  - [18, 51, 0.5]
  - [51, 52, 0.5]
  - [52, 57, 0.5]
